const express = require('express');
const { body } = require('express-validator');
const db = require('../../db/pool');
const { asyncHandler, ok, created, HttpError, paginated } = require('../../utils/http');
const { authenticate } = require('../../middleware/auth');
const { validate } = require('../../middleware');
const config = require('../../config');
const files = require('../../services/files');

const router = express.Router();
router.use(authenticate());

const csvEscape = (v) => {
  if (v == null) return '';
  const s = String(v);
  if (/[,"\n]/.test(s)) return `"${s.replace(/"/g, '""')}"`;
  return s;
};

router.get('/tasks', asyncHandler(async (req, res) => {
  const orgId = req.query.organization_id;
  if (!orgId) throw HttpError.badRequest('organization_id required');
  const r = await db.query(`SELECT t.*, p.name AS project_name, u.full_name AS assignee_name FROM tasks t JOIN projects p ON p.id=t.project_id LEFT JOIN users u ON u.id=t.assignee_id WHERE t.organization_id=$1`, [orgId]);
  const header = ['id','number','title','description','priority','status','assignee','project','due_date','completed_at','created_at'];
  const rows = [header.join(',')];
  for (const t of r.rows) rows.push([t.id, t.number, csvEscape(t.title), csvEscape(t.description || ''), t.priority, t.status_name || '', t.assignee_name || '', t.project_name, t.due_date, t.completed_at, t.created_at].join(','));
  res.setHeader('Content-Type', 'text/csv; charset=utf-8');
  res.setHeader('Content-Disposition', `attachment; filename="tasks-${Date.now()}.csv"`);
  return res.send(rows.join('\n'));
}));

router.get('/projects', asyncHandler(async (req, res) => {
  const orgId = req.query.organization_id;
  if (!orgId) throw HttpError.badRequest('organization_id required');
  const r = await db.query('SELECT * FROM projects WHERE organization_id=$1', [orgId]);
  const header = ['id','name','description','status','created_at'];
  const rows = [header.join(',')];
  for (const p of r.rows) rows.push([p.id, csvEscape(p.name), csvEscape(p.description || ''), p.status, p.created_at].join(','));
  res.setHeader('Content-Type', 'text/csv; charset=utf-8');
  res.setHeader('Content-Disposition', `attachment; filename="projects-${Date.now()}.csv"`);
  return res.send(rows.join('\n'));
}));

router.get('/json', asyncHandler(async (req, res) => {
  const orgId = req.query.organization_id;
  if (!orgId) throw HttpError.badRequest('organization_id required');
  const projects = await db.query('SELECT * FROM projects WHERE organization_id=$1', [orgId]);
  const tasks = await db.query('SELECT * FROM tasks WHERE organization_id=$1', [orgId]);
  const docs = await db.query('SELECT id, title, content FROM documents WHERE organization_id=$1', [orgId]);
  res.setHeader('Content-Disposition', `attachment; filename="apogee-export-${Date.now()}.json"`);
  return res.json({ exported_at: new Date().toISOString(), organization_id: orgId, projects: projects.rows, tasks: tasks.rows, documents: docs.rows });
}));

// PDF export — returns a simple HTML that can be printed to PDF, or uses puppeteer if available
router.post('/pdf', [body('type').notEmpty(), body('entity_id').isUUID(), body('content').optional(), body('title').optional()], validate, asyncHandler(async (req, res) => {
  const title = req.body.title || 'Document';
  const content = req.body.content || '';
  // Build a simple but professional PDF-ready HTML
  const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>${title}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; color: #1a1a2e; line-height: 1.6; }
  h1 { font-size: 28px; border-bottom: 2px solid #6366f1; padding-bottom: 10px; }
  h2 { font-size: 22px; margin-top: 32px; color: #4338ca; }
  h3 { font-size: 18px; margin-top: 24px; }
  pre, code { background: #f3f4f6; padding: 12px; border-radius: 6px; font-family: 'SF Mono', monospace; font-size: 13px; overflow-x: auto; }
  blockquote { border-left: 4px solid #6366f1; padding-left: 16px; color: #6b7280; margin: 16px 0; }
  img { max-width: 100%; }
  hr { border: none; border-top: 1px solid #e5e7eb; margin: 24px 0; }
  .footer { margin-top: 60px; padding-top: 20px; border-top: 1px solid #e5e7eb; font-size: 12px; color: #9ca3af; text-align: center; }
</style></head>
<body>
<h1>${escapeHtml(title)}</h1>
${content}
<div class="footer">Generated by Apogee · ${new Date().toLocaleDateString()}</div>
</body></html>`;
  res.setHeader('Content-Type', 'text/html');
  res.setHeader('Content-Disposition', `attachment; filename="${title.replace(/[^a-z0-9]/gi, '_')}.html"`);
  return res.send(html);
}));

function escapeHtml(s) {
  return String(s).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
}

module.exports = router;
